<a href="https://colab.research.google.com/github/Murnal98/work-on-iris-data/blob/main/Jaishree_Malode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import sklearn
from sklearn import datasets
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [ ]:
jm = pd.read_csv("/content/Iris.csv")
jm

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [ ]:
import numpy as np

In [ ]:
x = jm.iloc[:,1:5]
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
y = jm.iloc[:,5].values
y

 

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_s2 = LabelEncoder()
jm=labelencoder_s2.fit_transform(y)
jm


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split               
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2) 

In [ ]:
from sklearn.linear_model import LogisticRegression   
logmodel= LogisticRegression()
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
jm=logmodel.predict(x_test)
jm

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [ ]:
y_test

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [ ]:
from sklearn.metrics import confusion_matrix 
confusion_matrix(y_test,jm)

array([[14,  0,  0],
       [ 0,  7,  0],
       [ 0,  0,  9]])

In [ ]:
30/30

1.0

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn= KNeighborsClassifier(n_neighbors=5,metric='minkowski', p=2)
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred=classifier_knn.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0,  7,  0],
       [ 0,  0,  9]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier_nb =GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred=classifier_nb.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0,  7,  0],
       [ 0,  0,  9]])

In [ ]:
29/30

0.9666666666666667

In [ ]:
from sklearn.svm import SVC
classifier_svm_sigmoid =SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [ ]:
y_pred=classifier_svm_sigmoid.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[ 0, 14,  0],
       [ 0,  7,  0],
       [ 0,  9,  0]])

In [ ]:
8/30

0.26666666666666666

In [ ]:
from sklearn.svm import SVC
classifier_svm_linear =SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred=classifier_svm_linear.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0,  7,  0],
       [ 0,  1,  8]])

In [ ]:
27/30

0.9

In [ ]:
from sklearn.svm import SVC
classifier_svm_rbf= SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)

SVC()

In [ ]:
y_pred=classifier_svm_rbf.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0,  7,  0],
       [ 0,  1,  8]])

In [ ]:
27/30

0.9

In [ ]:
from sklearn.svm import SVC
classifier_svm_poly=SVC(kernel='poly')
classifier_svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [ ]:
y_pred=classifier_svm_poly.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0,  7,  0],
       [ 0,  0,  9]])

In [ ]:
28/30

0.9333333333333333

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt =DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
y_pred=classifier_dt.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0,  7,  0],
       [ 0,  1,  8]])

In [ ]:
26/30

0.8666666666666667

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf=RandomForestClassifier(n_estimators=3,criterion='entropy')
classifier_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [ ]:
y_pred=classifier_rf.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0,  7,  0],
       [ 0,  1,  8]])

In [ ]:
27/30

0.9